# Generated by Django 4.2 on 2023-04-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('name', 'cafe')},
        ),
    ]
