# Generated by Django 4.2 on 2023-04-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_cafe_owner_alter_menuitem_cafe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Short bio of the cafe'),
        ),
    ]
