# Generated by Django 4.2 on 2023-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_order_active_alter_orderitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
